// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMNhXO5g4-q1eXoWDuIcZXxxBkanSan0',
    appId: '1:212953381115:web:b23cfc0d36a2eff5cc985e',
    messagingSenderId: '212953381115',
    projectId: 'projeto-quiz-36bd2',
    authDomain: 'projeto-quiz-36bd2.firebaseapp.com',
    storageBucket: 'projeto-quiz-36bd2.firebasestorage.app',
    measurementId: 'G-YLZRYWX2XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJFsL9cKJD-rEx0ySwSqPL4wruyQCPXM',
    appId: '1:212953381115:android:ca6ce38b28e82da0cc985e',
    messagingSenderId: '212953381115',
    projectId: 'projeto-quiz-36bd2',
    storageBucket: 'projeto-quiz-36bd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjY3f6HkokyiYXk7rRVJRbQ413JRA9Sww',
    appId: '1:212953381115:ios:3fea1640c0d95f0dcc985e',
    messagingSenderId: '212953381115',
    projectId: 'projeto-quiz-36bd2',
    storageBucket: 'projeto-quiz-36bd2.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjY3f6HkokyiYXk7rRVJRbQ413JRA9Sww',
    appId: '1:212953381115:ios:3fea1640c0d95f0dcc985e',
    messagingSenderId: '212953381115',
    projectId: 'projeto-quiz-36bd2',
    storageBucket: 'projeto-quiz-36bd2.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlMNhXO5g4-q1eXoWDuIcZXxxBkanSan0',
    appId: '1:212953381115:web:c848028ee7c328e6cc985e',
    messagingSenderId: '212953381115',
    projectId: 'projeto-quiz-36bd2',
    authDomain: 'projeto-quiz-36bd2.firebaseapp.com',
    storageBucket: 'projeto-quiz-36bd2.firebasestorage.app',
    measurementId: 'G-7BCNTR6TZW',
  );
}
